spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: baeldung_route
              uri: http://baeldung.com
              predicates:
                - Path=/baeldung/
management:
  endpoints:
    web:
      exposure:
        include: "*"