spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: baeldung_route
              uri: http://baeldung.com
              predicates:
                - Path=/baeldung/
            - id: rating_route
              uri: http://localhost:8084
              predicates:
                - Path=/rating-service/**
              filters:
                - RewritePath=/rating-service/?(?<remaining>.*), /$\{remaining}
management:
  endpoints:
    web:
      exposure:
        include: "*"